### ISSUE TITLE
Copy to clipboard component

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#103]
When pressing on the "Share" button, copy the solution URL to the clipboard, and a messages pops and saying "Copied!"
![image](https://github.com/noams24/Kef-Code/assets/80849999/ff4de7d7-54d0-42bf-a027-8f0b8eeb9e7d)

Example in Leetcode: 
https://leetcode.com/problems/two-sum/description/
![image](https://github.com/noams24/Kef-Code/assets/80849999/3209340e-6b72-4342-b382-de689cd1121c)

link to component: https://github.com/noams24/Kef-Code/blob/main/src/layouts/components/workSpace/solutionSection/SolutionSection.tsx

In line 213: `      {isCopied && (
        <div className=" text-green-500">
          <AiFillCheckCircle/>
          הכתובת הועתקה!</div>
      )}`

Bonus: add animation

**Comment by codeomi** [comment]
Hi, with `handleShare` function @noams24 seems to be have taken care of the issue. I guess now you can delete the `copyToClipboard` function used on line : 160 which serves no purpose on the current code and used no where.

You can add animation to the text which shows when copied by adding some transition to it, since it is only visible for 2 seconds adding anything more serves no purpose to it (simple yet elegant).

Feel free to tag me if any more issues arrive.

**Comment by noams24** [comment]
@codeomi Oops I forgot to delete those lines lol.
I want the component to be fixed under the header, like in LeetCode.
Currently it looks like this: 
![image](https://github.com/noams24/Kef-Code/assets/80849999/9a991e11-4b2b-49c4-9a7c-03fba7d10011)

**Comment by codeomi** [comment]
@noams24 No worries, can you send me the URL to the component where it is used in UI (having trouble due to language gap). So that I can paste it ahead of `localhost`.

**Comment by codeomi** [comment]
Hey @noams24,
I have understood your requirement regarding a pop up to be displayed whenever uses clicks on the share button.

What you can do is use `snackbar` from the Material UI library, which is fairly easy to use.

Steps:-

- ` npm i @mui/material @emotion/react @emotion/styled`
-  Make a common component for the pop up to show (https://mui.com/material-ui/react-snackbar/)
- Use dynamic props according the message you want to show and the theme

**Comment by noams24** [comment]
@codeomi Good solution, thanks!
