### ISSUE TITLE
User page - Search and filter component

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#105]
Link to component: https://github.com/noams24/Kef-Code/blob/main/src/app/user/%5Bname%5D/User.tsx
![image](https://github.com/noams24/Kef-Code/assets/80849999/bd5854b8-9b1f-4292-b0c3-e488e3142c52)
In the user page, add a component that will allow to search and filter solutions by:

- last update
- course name

Maybe an example: https://maakaf-website.vercel.app/projects

**Comment by eyalyehia** [comment]
assign me
