### ISSUE TITLE
Fix Timer CSS

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#113]
Link to component: https://github.com/noams24/Kef-Code/blob/main/src/layouts/components/topBar/Timer.tsx
![image](https://github.com/noams24/Kef-Code/assets/80849999/241911af-7e89-499d-9fc2-5a583c773572)

![image](https://github.com/noams24/Kef-Code/assets/80849999/1dc21ea1-fdf6-4f5e-b000-856b46a4cf1e)

The buttons changing size every second for some reason

**Comment by lchauha** [comment]
Hi @noams24 I would like to work on this issue. Please assign this to me

**Comment by noams24** [comment]
Fixed
