### ISSUE TITLE
There is a section with mission questions

### ISSUE THREAD

**Issue by Tamir198** [noams24/Kef-Code#122]
This is the section with missing questions on it: 

![image](https://github.com/noams24/Kef-Code/assets/34707669/6889a4d4-5d1b-40f5-898e-7554fafaccf4)
 
 The browser tab will display undefined as well : 
 
 
![image](https://github.com/noams24/Kef-Code/assets/34707669/8bf3f792-1d3d-4137-9209-15f40a0696be)

**Comment by noams24** [comment]
@Tamir198 Thanks for opening an issue, fixed.
