### ISSUE TITLE
Math Shortcuts page

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#125]
Add a Math Shortcuts page.
Example:
https://www.assafmanor.co.il/latex/

The shortcuts are taken from here: https://cortexjs.io/mathlive/reference/commands/

current work: https://github.com/noams24/Kef-Code/tree/table/src/app/shortcuts

**Comment by DavidMarom** [comment]
@noams24 Do we have to put a LaTex keyboard on that page, or just a list of shortcuts?
Where do you want to put a link to the page? at the top nav-bar?

**Comment by DavidMarom** [comment]
@noams24 can you assign this to me please?
