### ISSUE TITLE
split-react bug

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#13]
when trying to run the code:

```
import Split from 'react-split'

<Split
    className="split"
>
    <div></div>
    <div></div>
</Split>
```
I get the error:
![image](https://github.com/noams24/Kef-Code/assets/80849999/ff96ba27-1528-47bf-bd83-855d02b9fdb8)

**Comment by noams24** [comment]
fixed

**Comment by sinhaniik** [comment]
hy @noams24 i am going through the same issue could you help me out 

I got this error when i am trying to use the `react-split`
```tsx
import React from 'react';
import Split from "react-split"
import ProblemStatement from "@/components/problemStatement/problemStatement";

type Props = {};
const Workspace = (props: Props) => {
    return (
        <Split className="split">
            <ProblemStatement/>
            <div>editor</div>
        </Split>
    );
};

export default Workspace
``` 
when i run `npm run dev` an error poped up

 __Server Error__
__TypeError: Object prototype may only be an Object or null: undefined__
__This error happened while generating the page. Any console logs will be displayed in the terminal window.__

i did everything which i can like re-install the package , dubugging but i failed to fix this error
here is `package.json` 
```json 
{
  "name": "leetcode-cl",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "20.4.9",
    "@types/react": "18.2.20",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.14",
    "firebase": "^10.3.0",
    "next": "13.4.13",
    "postcss": "8.4.27",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-firebase-hooks": "^5.1.1",
    "react-icons": "^4.10.1",
    "react-split": "^2.0.14",
    "react-toastify": "^9.1.3",
    "react-youtube": "^10.1.0",
    "recoil": "^0.7.7",
    "tailwindcss": "3.3.3",
    "typescript": "5.1.6"
  }
}

```

**Comment by noams24** [comment]
@sinhaniik I forgot how I fixed it, in my package is:

```
"react-split": "^2.0.14",
"split.js": "^1.6.0",
```
Check in my package maybe you forgot to install some dependency

In the website https://www.npmjs.com/package/react-split?activeTab=dependencies
they also require "prop type" library

**Comment by sinhaniik** [comment]
so what should i do, `install these extra packages` ?? or delete `node modules folder` and reinstall all the package ?

**Comment by noams24** [comment]
I think try to install those extra packages

**Comment by sinhaniik** [comment]
i just checked my `node modules` and found that it got both the packages installed `prop-types` and `split.js`

**Comment by sinhaniik** [comment]
the issue has been resolved
