### ISSUE TITLE
Responsive Top bar

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#142]
![image](https://github.com/noams24/Kef-Code/assets/80849999/ff4d93f3-b2d8-4d97-b884-f5fb11e4949d)

1.  Make the top bar responsive for small screens.
2. Clicking on the timer makes the breadcrumbs move to the left

Link to component: https://github.com/noams24/Kef-Code/tree/main/src/layouts/components/topBar

**Comment by Mohit-3007** [comment]
Hi @noams24 ,

I would like to do the same, kindly assign this to me

**Comment by noams24** [comment]
@Mohit-3007 I assigned you.
A good example would be like this: https://leetcode.com/problems/two-sum/ 
Thanks!

**Comment by noams24** [comment]
@Mohit-3007 Hi, when do you think you will finish this issue?
