### ISSUE TITLE
Fix toolbar CSS

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#33]
![image](https://github.com/noams24/Kef-Code/assets/80849999/caa87e77-78f3-4846-a33a-a1f16a527cac)
link to the component: https://github.com/noams24/Kef-Code/blob/main/src/layouts/editor/plugins/ToolbarPlugin/index.tsx
The toolbar isn't in the top of the text editor component,
the user can't see all the boxes.
To solve this problem, maybe make the boxes smaller and add flex-wrap
example in this website: https://platform.stratascratch.com/technical/2451-netflix-clone

**Comment by OshriAsulin** [comment]
can I take this issue?

**Comment by noams24** [comment]
> can I take this issue?

Yes! Check my comment on the PR
