### ISSUE TITLE
Fix toolbar gap

### ISSUE THREAD

**Issue by RoyTennenbaum** [noams24/Kef-Code#39]
Toolbar has a weird gap and should be attached to the edges of the split screen.
Attached screenshot below, note the arrows I marked:

![image](https://github.com/noams24/Kef-Code/assets/121032859/f05a2f1d-291d-4624-be60-d662f436dc98)

**Comment by RoyTennenbaum** [comment]
The up arrow is marked a bit too tall but you get the gist of it ;)

**Comment by noams24** [comment]
Done
