### ISSUE TITLE
Fix the text in the courses page

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#46]
![image](https://github.com/noams24/Kef-Code/assets/80849999/ecc9ba69-fbc7-4abb-9b30-26146e5b5fdc)
Align the text to the center and if it is overflowing add new rows.
In addition, add black background to the text so it will be more visible
![image](https://github.com/noams24/Kef-Code/assets/80849999/e18e081f-9e66-4047-a9d9-57d1eb22deb5)

**Comment by Bellavely** [comment]
Hi is that ok?
on light mode:  
![image](https://github.com/noams24/Kef-Code/assets/90250915/2713d0d9-2c4d-45a3-8be4-289454c4f8b8)
on dark mode : 
![image](https://github.com/noams24/Kef-Code/assets/90250915/5c2ded33-7134-4511-92d8-4c0bb7d6fdbf)
If its ok, can  I have this pull request?

**Comment by noams24** [comment]
Yes it looks good! Thanks

**Comment by Bellavely** [comment]
I fixed the title and the score now it looks better, Can you assign  me to this issue? 
![image](https://github.com/noams24/Kef-Code/assets/90250915/6a0d7836-c19c-4f6e-bd0e-0bb259ccf4e1)

**Comment by Bellavely** [comment]
#64
