### ISSUE TITLE
sorting the solutions from people doesn't work well

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#52]
the "refetch()" function doesn't work correctly after selecting sort by
![image](https://github.com/noams24/Kef-Code/assets/80849999/fff048f4-9399-4d65-9fa3-45981e0cdbab)

link to component:
https://github.com/noams24/Kef-Code/blob/main/src/layouts/components/workSpace/solutionSection/SolutionSection.tsx

**Comment by shiralima** [comment]
I will do that

**Comment by shiralima** [comment]
I will do that

**Comment by noams24** [comment]
I fixed it by changing the query key to `queryKey: ["solution", problemId, page, sortBy]`
