### ISSUE TITLE
Max height and width of the video solution

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#71]
![image](https://github.com/noams24/Kef-Code/assets/80849999/30bcedb2-11d6-4e38-8e29-85c432864592)
The height and width of the video are to big when pushing the split screen to the right

Link to component: https://github.com/noams24/Kef-Code/blob/main/src/layouts/components/workSpace/solutionSection/SolutionSection.tsx

https://github.com/noams24/Kef-Code/blob/main/src/layouts/shortcodes/Youtube.tsx

**Comment by eyalyehia** [comment]
assign me
