### ISSUE TITLE
Redesign the status component

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#72]
![image](https://github.com/noams24/Kef-Code/assets/80849999/deeece8e-4e65-489f-a8c7-efbc6a2b52d0)

Display only the icon instread of text, and when hovering display text

Link to component: https://github.com/noams24/Kef-Code/blob/main/src/layouts/components/Status.tsx 

*Note that it is seen only if the user is logged in.

**Comment by eyalyehia** [comment]
assign me
