### ISSUE TITLE
Images not loaded

### ISSUE THREAD

**Issue by Tamir198** [noams24/Kef-Code#8]
On the website, a lot of images are broken it seems :

![image](https://github.com/noams24/Kef-Code/assets/34707669/052a403a-7a12-4d3a-932c-6b52d68f48ac)

**Comment by noams24** [comment]
It's just a demo, in the future it will be like this:
![image](https://github.com/noams24/Kef-Code/assets/80849999/bf4c0e41-fd5e-4f4b-8441-91913e147d72)
check the issue for the card component
