### ISSUE TITLE
Solution Card

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#80]
![image](https://github.com/noams24/Kef-Code/assets/80849999/66e6b9de-baa2-4217-9a65-8469ae5598b2)
Make it look better lol
Link to the component: https://github.com/noams24/Kef-Code/blob/main/src/layouts/components/workSpace/solutionSection/SolutionCard.tsx

**Comment by veronicaarojas** [comment]
Hi, would be I be able to work on this issue?

**Comment by noams24** [comment]
Sure thanks!

**Comment by veronicaarojas** [comment]
Hi, 

I have been having an issue with configuring OAuth in my local machine.  When I attempt to sign in using google, I receive an error: 
```
`Error querying the database: Unknown authentication plugin `sha256_password'. PrismaClientInitializationError: 
Invalid `prisma.account.findUnique()` invocation:`
```

For context, my .env file contains the following (actual keys replaced): 
```
DATABASE_URL=mysql://root:randompassword@localhost:3306/mydb
NEXTAUTH_SECRET=...
GOOGLE_CLIENT_ID=...
GOOGLE_CLIENT_SECRET=...
```

Unfortunately, I have not been able to get around to styling yet, I hope to once this issue is resolved. Any help would be greatly appreciated!

**Comment by noams24** [comment]
@veronicaarojas Hi!
Did you try running the commands:
`yarn prisma generate`
`yarn prisma db push`

If you still receive an error you can work on this component on developer mode and using mock data.
Anyway I can send you an env file for developers via email.

**Comment by veronicaarojas** [comment]
@noams24 Thank you for getting back to me so quickly!

I now am receiving a new error:

```
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error State cookie was missing. {
  error: TypeError: State cookie was missing.
      at Object.use (webpack-internal:///(sc_server)/./node_modules/next-auth/core/lib/oauth/checks.js:122:27)
      at oAuthCallback (webpack-internal:///(sc_server)/./node_modules/next-auth/core/lib/oauth/callback.js:98:29)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.callback (webpack-internal:///(sc_server)/./node_modules/next-auth/core/routes/callback.js:18:79)
      at async AuthHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/core/index.js:202:38)
      at async NextAuthRouteHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:49:30)
      at async NextAuth._args$ (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:83:24)
      at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:249:37) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'google',
  message: 'State cookie was missing.'
```

This appears to be a common issue - see unresolved thread [here](https://github.com/nextauthjs/next-auth/discussions/7491)

Please let me know if you have any suggestions, otherwise developer mode and the env file would be incredibly helpful. Thank you!

**Comment by noams24** [comment]
I don't know how to solve this error, maybe change browser or change your settings in your google auth account.
Write me your email so I can send you the env file.

**Comment by veronicaarojas** [comment]
Thank you, my email is veronicaatkinsonrojas@gmail.com

**Comment by veronicaarojas** [comment]
@noams24 I managed to resolve the OAuth issue! 

I am now able to navigate the application on my local machine. 
Unfortunately, I cannot see any of the solution cards as none have been 'submitted' on my local machine and I am unsure how to make these appear. Any chance you could share the model data with me to populate my local database? 

Thank you!

**Comment by noams24** [comment]
@veronicaarojas I have sent you dump files

**Comment by noams24** [comment]
@veronicaarojas did you make any progress?

**Comment by veronicaarojas** [comment]
@noams24 hello! Yes I made a bit of progress but have been very busy as I just moved countries. Sorry for not keeping you updated. I can get back to it next week? Let me know if this works.

**Comment by noams24** [comment]
> @noams24 hello! Yes I made a bit of progress but have been very busy as I just moved countries. Sorry for not keeping you updated. I can get back to it next week? Let me know if this works. 
> 

Of course, there is no pressure 🙂

**Comment by veronicaarojas** [comment]
@noams24 hi again, just to update I haven't had a chance to complete. Thanks so much for your patience I will share as soon as I can
