### ISSUE TITLE
Delete Solution

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#87]
When the user want to delete a solution, open a warning modal before it get deleted (clicking on the trash icon)
![image](https://github.com/noams24/Kef-Code/assets/80849999/334c7427-7acc-4cd5-889b-ccd75a7d8e10)

The modal should look something like:
![image](https://github.com/noams24/Kef-Code/assets/80849999/d8ccc75b-83fb-4013-9d1a-97001726f0cd)

Link to component: 
https://github.com/noams24/Kef-Code/blob/main/src/layouts/components/modals/DeleteSolutionModal.tsx
https://github.com/noams24/Kef-Code/blob/main/src/layouts/components/workSpace/WorkSpace.tsx

**Comment by amabelleS** [comment]
hey:) I would love to take this issue.

**Comment by noams24** [comment]
> hey:) I would love to take this issue.

Thanks!

**Comment by amabelleS** [comment]
I am trying to start working on this issue, but I can't get signed up/in (some bug?) => and I can't save a solution if I'm not signed in.

**Comment by noams24** [comment]
> I am trying to start working on this issue, but I can't get signed up/in (some bug?) => and I can't save a solution if I'm not signed in.

Sorry for the delay, 
In the file /store/store, change the line
 `development: process.env.NODE_ENV === "development"` to `development: process.env.NODE_ENV !== "development"` .
In addition, you need to add an env file to connect it to a database. I can send you a mock env file via email or you can create your own.
Thanks! 👍

**Comment by amabelleS** [comment]
Hey:) 
There is a .env-example file with this params: 
DATABASE_URL=
NEXTAUTH_SECRET=

GOOGLE_CLIENT_ID= 
GOOGLE_CLIENT_SECRET=

The question is how do I fill it up - are we using MySQL as a DB? 
- Do I need to open a MySQL DB locally for my env, or is there a collective one for development?
- Do I need to fill in all the secrets? (NEXTAUTH_SECRET, GOOGLE_CLIENT_ID ,GOOGLE_CLIENT_SECRET)

**Comment by noams24** [comment]
> Hey:) There is a .env-example file with this params: DATABASE_URL= NEXTAUTH_SECRET=
> 
> GOOGLE_CLIENT_ID= GOOGLE_CLIENT_SECRET=
> 
> The question is how do I fill it up - are we using MySQL as a DB?
> 
> * Do I need to open a MySQL DB locally for my env, or is there a collective one for development?
> * Do I need to fill in all the secrets? (NEXTAUTH_SECRET, GOOGLE_CLIENT_ID ,GOOGLE_CLIENT_SECRET)

1. Yes, I am using MySQL.
2. You can open a local DB and then run the command   `yarn prisma db push`.
3. In order to log in you need to fill them.

The easiest solution I suggest is that I will send you a env file via email.
BTW, because it's a Frontend issue you don't really need all that.

**Comment by amabelleS** [comment]
> > Hey:) There is a .env-example file with this params: DATABASE_URL= NEXTAUTH_SECRET=
> > GOOGLE_CLIENT_ID= GOOGLE_CLIENT_SECRET=
> > The question is how do I fill it up - are we using MySQL as a DB?
> > 
> > * Do I need to open a MySQL DB locally for my env, or is there a collective one for development?
> > * Do I need to fill in all the secrets? (NEXTAUTH_SECRET, GOOGLE_CLIENT_ID ,GOOGLE_CLIENT_SECRET)
> 
> 1. Yes, I am using MySQL.
> 2. You can open a local DB and then run the command   `yarn prisma db push`.
> 3. In order to log in you need to fill them.
> 
> The easiest solution I suggest is that I will send you a env file via email. BTW, because it's a Frontend issue you don't really need all that.

OK, first I think the .env file will help me to get started. You can send it to: amabelledev@gmail.com

I downloaded MySQL (again, sort of a new laptop), and created the local db. I created a NEXTAUTH_SECRET in my bash terminal. But I think I need the  GOOGLE_CLIENT_ID ,GOOGLE_CLIENT_SECRET of the project? I tried to put the ones I created myself, but maybe I'm missing something. That's were I'm stuck now: 

<img width="388" alt="image" src="https://github.com/noams24/Kef-Code/assets/45571546/2dca58cb-31f9-4c8d-8f1c-d2bab6e8b8a4">

Error 400: redirect_uri_mismatch

אין לך אפשרות להיכנס לאפליקציה הזו כי היא לא עומדת בדרישות מדיניות OAuth 2.0 של Google.

אם את/ה המפתח/ת של האפליקציה, עליך לרשום ב-Google Cloud Console את ה-URI של ההפניה האוטומטית.
Request details: redirect_uri=http://localhost:3000/api/auth/callback/google

**Comment by noams24** [comment]
> amabelleS

I have sent you the env file, tell me if it works :)

**Comment by amabelleS** [comment]
> > amabelleS
> 
> I have sent you the env file, tell me if it works :)

Yay, I'm in:)

<img width="146" alt="image" src="https://github.com/noams24/Kef-Code/assets/45571546/8f163fb8-7019-4d39-b315-89d294fe7dfc">

I used the  GOOGLE_CLIENT_ID & GOOGLE_CLIENT_SECRET in the .env file that you sent me.
