### ISSUE TITLE
Add CONTRIBUTING.md & CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by amabelleS** [noams24/Kef-Code#88]
I can make adjustments to similar files I made to other projects.

**Comment by noams24** [comment]
Sure, why not!

**Comment by amabelleS** [comment]
Sorry, I forgot about that for a while:) But now on it.

Would you like for me to add any links to the CONTRIBUTING.md? 
like this one, I added to another project: https://www.youtube.com/watch?v=IVNxfbHNHZk

Any tutorials you would like attached.

**Comment by noams24** [comment]
@amabelleS Do whatever you think is right and will help others 👍
