### ISSUE TITLE
Adding installation guides

### ISSUE THREAD

**Issue by Tamir198** [noams24/Kef-Code#9]
Hey, I saw this : 

![image](https://github.com/noams24/Kef-Code/assets/34707669/3d01d371-ebe7-4bbb-b26c-0db759f4bb18)

I was thinking that it could be nice to add the `npm install` part to help the new contributors run the project without any problems.

This may seem trivial but I think that it won't hurt.

**Comment by noams24** [comment]
I will add it, thanks!
