### ISSUE TITLE
User page

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#92]
Add user page
Link to component: https://github.com/noams24/Kef-Code/blob/main/src/app/user/%5Bname%5D/page.tsx

Examples:
matheditor:
![image](https://github.com/noams24/Kef-Code/assets/80849999/d02faf0d-8848-4ce4-8bab-3133c6b042bf)
https://matheditor.me/user/288c84d0-8b13-4206-8b12-b14c567e65fe
https://github.com/ibastawisi/matheditor/blob/master/src/components/User.tsx

LeetCode:
![image](https://github.com/noams24/Kef-Code/assets/80849999/3a127bf9-8547-4112-a37a-70eefa6de8eb)

kaggle
![image](https://github.com/noams24/Kef-Code/assets/80849999/331f6444-dfa7-4ba0-83fd-14fe46d51748)
https://www.kaggle.com/syeddanish

**Comment by MZT7** [comment]
how can  i contribute to this

**Comment by noams24** [comment]
> how can i contribute to this

I think the first example is good, but you can do whatever you want as long as it's looks fine.
I only need help with the Frontend.

You can use this mock data for the user data and his submissions data:

```
import { db } from "@/lib/db";
import { UserAvatar } from "@/components/UserAvatar";
import { humanize, slugify } from "@/lib/utils/textConverter";

const User = async ({ params }: { params: { name: string } }) => {

  try {
    // const user: any = await db.user.findUnique({
    //   where: {
    //     username: decodeURIComponent(params.name),
    //   },
    // });
    // if (!user) return <div>No user found</div>;

    const user = {
      id: 'clgfjsgfjfg',
      name: 'noam',
      email: 'noam@gmail.com',
      emailVerified: null,
      username: 'noam',
      image: 'https://utfs.io/f/5deaa94c-25cb-4512-a7a0-46028e02e1f7_albert-einstein-7476672_1280.png',
      role: 'USER'
    }

    // console.log(user)

    // const data: any = await db.submissions.findMany({
    //   where: {
    //     userId: user.id,
    //     isPublic: true,
    //   },
    // });

   const data = [
      {
        id: '1',
        userId: 'clgfjsgfjfg',
        problemId: 1,
        content: { root: [Object] },
        createdAt: new Date('2023-08-20T19:34:51.140Z'),
        updatedAt: new Date('2023-08-20T19:34:51.140Z'),
        isPublic: true,
        videoUrl: 'B1J6Ou4q8vE'
      },
      {
        id: '3',
        userId: 'clgfjsgfjfg',
        problemId: 1,
        content: { root: [Object] },
        createdAt: new Date('2023-08-20T19:34:51.140Z'),
        updatedAt: new Date('2023-08-20T19:34:51.140Z'),
        isPublic: true,
        videoUrl: null
      },
      {
        id: 'cllkt8q460001mg08cgwccsat',
        userId: 'clgfjsgfjfg',
        problemId: 1,
        content: { root: [Object] },
        createdAt: new Date('2023-08-20T19:34:51.140Z'),
        updatedAt: new Date('2023-08-20T19:34:51.140Z'),
        isPublic: true,
        videoUrl: null
      },
      {
        id: 'cllkt9i0r0001mh08ikegn95k',
        userId: 'clgfjsgfjfg',
        problemId: 1,
        content: { root: [Object] },
        createdAt: new Date('2023-08-20T19:34:51.140Z'),
        updatedAt: new Date('2023-08-20T19:34:51.140Z'),
        isPublic: true,
        videoUrl: null
      },
      {
        id: 'cllkta3k20003mh08dlgbi8mp',
        userId: 'clgfjsgfjfg',
        problemId: 1,
        content: { root: [Object] },
        createdAt: new Date('2023-08-20T19:34:51.140Z'),
        updatedAt: new Date('2023-08-20T19:34:51.140Z'),
        isPublic: true,
        videoUrl: null
      },
    ]

    // console.log(data);
    return (
      <div className="pt-8">
        <div className="flex justify-center items-center mb-2">
          <h2>{humanize(user.username)} </h2>
          <UserAvatar
            user={{ name: "" || null, image: user.image || null }}
            className="h-32 w-32 -mt-1 ml-2 inline-block"
          />
        </div>
      </div>
    );
  } catch {}
};

export default User;

```

**Comment by MZT7** [comment]
> > how can i contribute to this
> 
> I think the first example is good, but you can do whatever you want as long as it's looks fine. I only need help with the Frontend.
> 
> You can use this mock data for the user data and his submissions data:
> 
> ```
> import { db } from "@/lib/db";
> import { UserAvatar } from "@/components/UserAvatar";
> import { humanize, slugify } from "@/lib/utils/textConverter";
> 
> const User = async ({ params }: { params: { name: string } }) => {
> 
>   try {
>     // const user: any = await db.user.findUnique({
>     //   where: {
>     //     username: decodeURIComponent(params.name),
>     //   },
>     // });
>     // if (!user) return <div>No user found</div>;
> 
>     const user = {
>       id: 'clgfjsgfjfg',
>       name: 'noam',
>       email: 'noam@gmail.com',
>       emailVerified: null,
>       username: 'noam',
>       image: 'https://utfs.io/f/5deaa94c-25cb-4512-a7a0-46028e02e1f7_albert-einstein-7476672_1280.png',
>       role: 'USER'
>     }
> 
>     // console.log(user)
> 
>     // const data: any = await db.submissions.findMany({
>     //   where: {
>     //     userId: user.id,
>     //     isPublic: true,
>     //   },
>     // });
> 
>    const data = [
>       {
>         id: '1',
>         userId: 'clgfjsgfjfg',
>         problemId: 1,
>         content: { root: [Object] },
>         createdAt: new Date('2023-08-20T19:34:51.140Z'),
>         updatedAt: new Date('2023-08-20T19:34:51.140Z'),
>         isPublic: true,
>         videoUrl: 'B1J6Ou4q8vE'
>       },
>       {
>         id: '3',
>         userId: 'clgfjsgfjfg',
>         problemId: 1,
>         content: { root: [Object] },
>         createdAt: new Date('2023-08-20T19:34:51.140Z'),
>         updatedAt: new Date('2023-08-20T19:34:51.140Z'),
>         isPublic: true,
>         videoUrl: null
>       },
>       {
>         id: 'cllkt8q460001mg08cgwccsat',
>         userId: 'clgfjsgfjfg',
>         problemId: 1,
>         content: { root: [Object] },
>         createdAt: new Date('2023-08-20T19:34:51.140Z'),
>         updatedAt: new Date('2023-08-20T19:34:51.140Z'),
>         isPublic: true,
>         videoUrl: null
>       },
>       {
>         id: 'cllkt9i0r0001mh08ikegn95k',
>         userId: 'clgfjsgfjfg',
>         problemId: 1,
>         content: { root: [Object] },
>         createdAt: new Date('2023-08-20T19:34:51.140Z'),
>         updatedAt: new Date('2023-08-20T19:34:51.140Z'),
>         isPublic: true,
>         videoUrl: null
>       },
>       {
>         id: 'cllkta3k20003mh08dlgbi8mp',
>         userId: 'clgfjsgfjfg',
>         problemId: 1,
>         content: { root: [Object] },
>         createdAt: new Date('2023-08-20T19:34:51.140Z'),
>         updatedAt: new Date('2023-08-20T19:34:51.140Z'),
>         isPublic: true,
>         videoUrl: null
>       },
>     ]
> 
>     // console.log(data);
>     return (
>       <div className="pt-8">
>         <div className="flex justify-center items-center mb-2">
>           <h2>{humanize(user.username)} </h2>
>           <UserAvatar
>             user={{ name: "" || null, image: user.image || null }}
>             className="h-32 w-32 -mt-1 ml-2 inline-block"
>           />
>         </div>
>       </div>
>     );
>   } catch {}
> };
> 
> export default User;
> ```

i am trying to local the url in my local machine

**Comment by MZT7** [comment]
> > > how can i contribute to this
> > 
> > 
> > I think the first example is good, but you can do whatever you want as long as it's looks fine. I only need help with the Frontend.
> > You can use this mock data for the user data and his submissions data:
> > ```
> > import { db } from "@/lib/db";
> > import { UserAvatar } from "@/components/UserAvatar";
> > import { humanize, slugify } from "@/lib/utils/textConverter";
> > 
> > const User = async ({ params }: { params: { name: string } }) => {
> > 
> >   try {
> >     // const user: any = await db.user.findUnique({
> >     //   where: {
> >     //     username: decodeURIComponent(params.name),
> >     //   },
> >     // });
> >     // if (!user) return <div>No user found</div>;
> > 
> >     const user = {
> >       id: 'clgfjsgfjfg',
> >       name: 'noam',
> >       email: 'noam@gmail.com',
> >       emailVerified: null,
> >       username: 'noam',
> >       image: 'https://utfs.io/f/5deaa94c-25cb-4512-a7a0-46028e02e1f7_albert-einstein-7476672_1280.png',
> >       role: 'USER'
> >     }
> > 
> >     // console.log(user)
> > 
> >     // const data: any = await db.submissions.findMany({
> >     //   where: {
> >     //     userId: user.id,
> >     //     isPublic: true,
> >     //   },
> >     // });
> > 
> >    const data = [
> >       {
> >         id: '1',
> >         userId: 'clgfjsgfjfg',
> >         problemId: 1,
> >         content: { root: [Object] },
> >         createdAt: new Date('2023-08-20T19:34:51.140Z'),
> >         updatedAt: new Date('2023-08-20T19:34:51.140Z'),
> >         isPublic: true,
> >         videoUrl: 'B1J6Ou4q8vE'
> >       },
> >       {
> >         id: '3',
> >         userId: 'clgfjsgfjfg',
> >         problemId: 1,
> >         content: { root: [Object] },
> >         createdAt: new Date('2023-08-20T19:34:51.140Z'),
> >         updatedAt: new Date('2023-08-20T19:34:51.140Z'),
> >         isPublic: true,
> >         videoUrl: null
> >       },
> >       {
> >         id: 'cllkt8q460001mg08cgwccsat',
> >         userId: 'clgfjsgfjfg',
> >         problemId: 1,
> >         content: { root: [Object] },
> >         createdAt: new Date('2023-08-20T19:34:51.140Z'),
> >         updatedAt: new Date('2023-08-20T19:34:51.140Z'),
> >         isPublic: true,
> >         videoUrl: null
> >       },
> >       {
> >         id: 'cllkt9i0r0001mh08ikegn95k',
> >         userId: 'clgfjsgfjfg',
> >         problemId: 1,
> >         content: { root: [Object] },
> >         createdAt: new Date('2023-08-20T19:34:51.140Z'),
> >         updatedAt: new Date('2023-08-20T19:34:51.140Z'),
> >         isPublic: true,
> >         videoUrl: null
> >       },
> >       {
> >         id: 'cllkta3k20003mh08dlgbi8mp',
> >         userId: 'clgfjsgfjfg',
> >         problemId: 1,
> >         content: { root: [Object] },
> >         createdAt: new Date('2023-08-20T19:34:51.140Z'),
> >         updatedAt: new Date('2023-08-20T19:34:51.140Z'),
> >         isPublic: true,
> >         videoUrl: null
> >       },
> >     ]
> > 
> >     // console.log(data);
> >     return (
> >       <div className="pt-8">
> >         <div className="flex justify-center items-center mb-2">
> >           <h2>{humanize(user.username)} </h2>
> >           <UserAvatar
> >             user={{ name: "" || null, image: user.image || null }}
> >             className="h-32 w-32 -mt-1 ml-2 inline-block"
> >           />
> >         </div>
> >       </div>
> >     );
> >   } catch {}
> > };
> > 
> > export default User;
> > ```
> 
> i am trying to local the url in my local machine

trying to locate user route on the web

**Comment by noams24** [comment]
@MZT7 You mean url like this? https://kef-code.vercel.app/user/נועם

**Comment by MZT7** [comment]
@noams24  yeah  thanks

**Comment by MZT7** [comment]
@noams24  yeah  thanks

**Comment by MZT7** [comment]
@noams24 I am trying to login to view the user locally and work on the frontend but it gives me nextauth error and googleID error

**Comment by MZT7** [comment]
what is the redirect_uri for google signup for nextauth() login, so i can put it in my google oauthclient configuration

**Comment by noams24** [comment]
@MZT7 I did like this:
![image](https://github.com/noams24/Kef-Code/assets/80849999/952f7e6f-7e66-4e1f-9928-0f820715a83a)

If you want to save time on configuration and stuff like that, I can send you an env file via email

**Comment by MZT7** [comment]
@noams24 please do send it😌

**Comment by noams24** [comment]
@MZT7  send me your email

**Comment by MZT7** [comment]
@noams24 duzioristo@gmail.com

**Comment by MZT7** [comment]
> @MZT7 You mean url like this? [https://kef-code.vercel.app/user/נועם](https://kef-code.vercel.app/user/%D7%A0%D7%95%D7%A2%D7%9D)

this route only appears on production while locally it shows "no user found"

**Comment by noams24** [comment]
@MZT7 try now

**Comment by MZT7** [comment]
> @MZT7 try now

works now👍

**Comment by noams24** [comment]
@MZT7 Let me know when you are done bro so I will approve the PR.

**Comment by MZT7** [comment]
@noams24 i am done

**Comment by noams24** [comment]
Nice Thanks! @MZT7

**Comment by MZT7** [comment]
@noams24  no Problem
