### ISSUE TITLE
Header problem

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#93]
![image](https://github.com/noams24/Kef-Code/assets/80849999/87232d1d-b7b3-4667-a470-a38f6dfab360)

User logo and night mode should be on the left side
The problem only occurred when the display is medium or small screen

link to component: https://github.com/noams24/Kef-Code/blob/main/src/layouts/partials/Header.tsx

**Comment by ozn1907** [comment]
Hello,

The issue should be resolved, and the night mode is now positioned on the left side.

**Comment by noams24** [comment]
> Hello,
> 
> The issue should be resolved, and the night mode is now positioned on the left side.

Can you make pull request with that changes that you have made?

**Comment by noams24** [comment]
@ozn1907 Thanks bro! 👍
