### ISSUE TITLE
Header bug

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#96]
If the screen is very small, the logo jumps down
![image](https://github.com/noams24/Kef-Code/assets/80849999/3cc534cf-03c1-49b5-9c69-fdeddbdce435)

Link to component: https://github.com/noams24/Kef-Code/blob/main/src/layouts/partials/Header.tsx

**Comment by ozn1907** [comment]
Should be fixed now!

**Comment by vinhhung0306** [comment]
> If the screen is very small, the logo jumps down

Could I work on this one ?

**Comment by noams24** [comment]
@ozn1907  You are the best!
